left:
  controller_manager:
    ros__parameters:
      update_rate: 100

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      robotiq_gripper_controller:
        type: parallel_gripper_action_controller/GripperActionController

      robotiq_activation_controller:
        type: robotiq_controllers/RobotiqActivationController

  robotiq_gripper_controller:
    ros__parameters:
      joint: finger_joint
      max_effort_interface: "finger_joint/set_gripper_max_effort"
      max_velocity_interface: "finger_joint/set_gripper_max_velocity"
      max_effort: 50.0
      max_velocity: 0.5
      state_interfaces: ["position", "velocity"]
      allow_stalling: true
      stall_timeout: 0.05
      goal_tolerance: 0.02

  robotiq_activation_controller:
    ros__parameters:
      default: true


right:
  controller_manager:
    ros__parameters:
      update_rate: 100

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      robotiq_gripper_controller:
        type: parallel_gripper_action_controller/GripperActionController

      robotiq_activation_controller:
        type: robotiq_controllers/RobotiqActivationController

  robotiq_gripper_controller:
    ros__parameters:
      joint: finger_joint
      max_effort_interface: "finger_joint/set_gripper_max_effort"
      max_velocity_interface: "finger_joint/set_gripper_max_velocity"
      max_effort: 50.0
      max_velocity: 0.5
      state_interfaces: ["position", "velocity"]
      allow_stalling: true
      stall_timeout: 0.05
      goal_tolerance: 0.02

  robotiq_activation_controller:
    ros__parameters:
      default: true



#  Jazzy and newer: parallel_gripper_action_controller replaces gripper_controllers package
